export const RESTART_GAME = 'RESTART_GAME';
export const GENERATE_NUMBERS = 'GENERATE_NUMBERS';
export const PRESS_CARD_ITEM = 'PRESS_CARD_ITEM';
export const SET_CHECKED_INFO = 'SET_CHECKED_INFO';
export const END_GAME = 'END_GAME';